language: c

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

before_install:
    - cd src

install:
    - make travis-install

script:
    - make travis-test

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
